### ISSUE TITLE
Compile Error: quill-editor is not a helper

### ISSUE THREAD

**Issue by dirkdirk** [noppo-pro/ember-quill#2]
Actions
1. cd my-ember-app
1. $ ember install ember-quill  // But it doesn't seem to download or install anything.
1. Add `{{quill-editor value='test text' options=options textChange=(action 'updateText')}} ` to templates/application.hbs.
1. Cut and paste the Component Example from the README.MD into `controllers/application.js`
1. $ ember s

Console reports: `Compile Error: quill-editor is not a helper`

DEBUG: -------------------------------
DEBUG: Ember      : 2.10.2
DEBUG: Ember Data : 2.12.1
DEBUG: Firebase   : 3.7.2
DEBUG: EmberFire  : 0.0.0
DEBUG: jQuery     : 3.2.0
DEBUG: -------------------------------

My `package.json` does not have an entry for `ember-quill`.

Am I missing something?

**Comment by cspanring** [comment]
it looks like ember-quill has not been successfully installed in your app. see #3 , it seems there are some problems with the published package.

**Comment by jgelens** [comment]
The latest version 0.0.8 should work, it seems it's an issue with `yarn publish`. `npm publish` seems to work alright.
